const pCardData = [
  {
    bgImg: "1",
    profileImg: "",
    name: "Michael Angelo",
    team: "WebXDAO Developer",
    github: "",
    twitter: "",
    linkedin: "",
    title: "Blockchain: Disrupting Industries",
    desc: "Explore how blockchain revolutionizes traditional industries.",
    link: "",
  },
  {
    bgImg: "2",
    profileImg: "",
    name: "James Bond",
    team: "WebXDAO Developer",
    github: "",
    twitter: "",
    linkedin: "",
    title: "Secure Digital Assets with Blockchain",
    desc: "Discover the power of blockchain for securing digital assets.",
    link: "",
  },
  {
    bgImg: "3",
    profileImg: "",
    name: "Ron Smith",
    team: "WebXDAO Developer",
    github: "",
    twitter: "",
    linkedin: "",
    title: "Blockchain and Sustainability",
    desc: "Learn how blockchain drives positive change for sustainability.",
    link: "",
  },
  {
    bgImg: "4",
    profileImg: "",
    name: "Christian Pertti",
    team: "WebXDAO Developer",
    github: "",
    twitter: "",
    linkedin: "",
    title: "Blockchain: Future of Banking",
    desc: "Explore how blockchain reshapes banking with DeFi.",
    link: "",
  },
  {
    bgImg: "5",
    profileImg: "",
    name: "Chua Chan",
    team: "WebXDAO Developer",
    github: "",
    twitter: "",
    linkedin: "",
    title: "Blockchain in Healthcare",
    desc: "Transforming patient data management with blockchain.",
    link: "",
  },
  {
    bgImg: "6",
    profileImg: "",
    name: "Avendi Brucell",
    team: "WebXDAO Developer",
    github: "",
    twitter: "",
    linkedin: "",
    title: "Blockchain in Gaming",
    desc: "Powering the next generation of gaming with blockchain.",
    link: "",
  },
];

export default pCardData;