# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: npm
    init: npm install
    command: npm run start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: true
    master: true
    branches: true
    pullRequestsFromForks: true

vscode:
  extensions:
    - davidanson.vscode-markdownlint
    - astro-build.astro-vscode
