name: Other
description: Use this for any other issues. PLEASE do not create blank issues
title: "[OTHER]"
labels: ["awaiting triage"]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: "I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)"
          required: true
        - label: "I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
        - label: "I am a GSSoC'23 contributor"
          required: false
